# 0. Import Data

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('Churn.csv')

In [3]:
X = df.drop(['Churn', 'Customer ID'], axis=1)

In [4]:
X =  pd.get_dummies(X, drop_first=True).replace({False: 0, True: 1})
y = df['Churn'].apply(lambda x: 1 if x=='Yes' else 0)

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2)

In [6]:
y_train.head()

6829    0
537     0
974     1
6839    1
159     0
Name: Churn, dtype: int64

# 1. Import Dependencies

In [7]:
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense
from sklearn.metrics import accuracy_score

2023-10-11 19:07:23.652344: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-10-11 19:07:25.080266: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-10-11 19:07:25.080317: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-10-11 19:07:25.080653: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-10-11 19:07:25.090744: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-10-11 19:07:25.091283: I tensorflow/core/platform/cpu_feature_guard.cc:182] This Tens

# 2. Build and Compile Model

In [8]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_dim=len(X_train.columns)))
model.add(Dense(units=64, activation='relu'))
model.add(Dense(units=1, activation='sigmoid'))

In [19]:
model.compile(loss='binary_crossentropy', optimizer='sgd', metrics='accuracy')

# 3. Fit, Predict and Evaluate

In [20]:
model.fit(X_train, y_train, epochs=200, batch_size=32)

Epoch 1/200


2023-10-11 19:24:05.296191: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 295679720 exceeds 10% of free system memory.


177/177 [==============================] - 1s 3ms/step - loss: 0.4337 - accuracy: 0.7918
Epoch 2/200
177/177 [==============================] - 0s 2ms/step - loss: 0.4373 - accuracy: 0.7924
Epoch 3/200
177/177 [==============================] - 0s 2ms/step - loss: 0.4372 - accuracy: 0.7922
Epoch 4/200
177/177 [==============================] - 0s 3ms/step - loss: 0.4320 - accuracy: 0.7906
Epoch 5/200
177/177 [==============================] - 0s 2ms/step - loss: 0.4349 - accuracy: 0.7947
Epoch 6/200
177/177 [==============================] - 0s 2ms/step - loss: 0.4356 - accuracy: 0.7918
Epoch 7/200
177/177 [==============================] - 0s 2ms/step - loss: 0.4372 - accuracy: 0.7913
Epoch 8/200
177/177 [==============================] - 0s 2ms/step - loss: 0.4321 - accuracy: 0.7936
Epoch 9/200
177/177 [==============================] - 0s 2ms/step - loss: 0.4344 - accuracy: 0.7894
Epoch 10/200
177/177 [==============================] - 0s 2ms/step - loss: 0.4354 - accuracy: 0.7918
E

In [11]:
y_hat = model.predict(X_test)
y_hat = [0 if val < 0.5 else 1 for val in y_hat]

45/45 [==============================] - 0s 1ms/step


2023-10-11 19:09:50.141031: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 73933048 exceeds 10% of free system memory.


In [16]:
from sklearn.metrics import f1_score
f1_score(y_test, y_hat)

0.6388140161725067

In [12]:
accuracy_score(y_test, y_hat)


0.8097941802696949

# 4. Saving and Reloading

In [13]:
model.save('tfmodel')

INFO:tensorflow:Assets written to: tfmodel/assets


INFO:tensorflow:Assets written to: tfmodel/assets


In [14]:
del model 

In [15]:
model = load_model('tfmodel')

## 5. Create new models 

In [23]:
import tensorflow as tf

In [24]:
if tf.config.list_physical_devices('GPU'):
  print("TensorFlow **IS** using the GPU")
else:
  print("TensorFlow **IS NOT** using the GPU")

TensorFlow **IS NOT** using the GPU


In [25]:
x = tf.constant([[1., 2., 3.],
                 [4., 5., 6.]])

print(x)
print(x.shape)
print(x.dtype)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
(2, 3)
<dtype: 'float32'>


In [26]:
x+x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [27]:
x @ tf.transpose(x)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

In [28]:
y = tf.constant([[1., 1., 1.],
                 [1.,1.,1.]])

In [31]:
y@tf.transpose(y)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3., 3.],
       [3., 3.]], dtype=float32)>

In [32]:
tf.nn.softmax(x, axis=-1)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.09003057, 0.24472848, 0.66524094],
       [0.09003057, 0.24472848, 0.66524094]], dtype=float32)>

In [36]:
x = tf.Variable(1.0)
x

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>

In [37]:
def f(x):
    y = x**2 + 2*x + 4
    return y
print(f(x))

tf.Tensor(7.0, shape=(), dtype=float32)


In [38]:
with tf.GradientTape() as tape:
  y = f(x)
  

g_x = tape.gradient(y, x)  # g(x) = dy/dx
g_x

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

In [39]:
@tf.function
def my_func(x):
  print('Tracing.\n')
  return tf.reduce_sum(x)

In [40]:
x = tf.constant([1, 2, 3])
my_func(x)

Tracing.



<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [41]:
x = tf.constant([10, 9, 8])
my_func(x)

<tf.Tensor: shape=(), dtype=int32, numpy=27>

In [42]:
x = tf.constant([10.0, 9.1, 8.2], dtype=tf.float32)
my_func(x)

Tracing.



<tf.Tensor: shape=(), dtype=float32, numpy=27.3>